packaging_format = 2

id = "counter"
name = "Counter Web Analytics"
description.en = "Web Analytics made simple"
description.fr = "Web Analytics made simple"

version = "0.2~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://counter.dev/"
demo = "https://counter.dev/dashboard.html?demo=1"
admindoc = "https://yunohost.org/packaging_apps"
code = "https://github.com/ihucos/counter.dev-selfhost"

[integration]
yunohost = ">= 11.1.20"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/ihucos/counter.dev-selfhost/releases/download/0.2/cntr-linux-amd64"
        sha256 = "3fef2a150b67be45182228eebd8f8f748a245d192e6d723388d3c351e547bcf6"
        in_subdir = false
        extract = false
        rename = "cntr"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
